console.log(Math)//la variable math contiene todos los metodos que son para realizar operaciones matematicas complejas dentro del lenguaje
console.log(Math.PI)
console.log(Math.abs(-212312.124124))
console.log(Math.ceil(7.77))
console.log(Math.PI) // Devuelve el valor de PI (3.141592653589793)
console.log(Math.abs(-212312.124124)) // Devuelve el valor absoluto (212312.124124)
console.log(Math.ceil(7.77)) // Devuelve el entero más pequeño mayor o igual que un número (8)
console.log(Math.floor(7.77)) // Devuelve el entero más grande menor o igual que un número (7)
console.log(Math.round(7.77)) // Devuelve el valor de un número redondeado al entero más cercano (8)
console.log(Math.max(10, 20, 30)) // Devuelve el número más grande de los argumentos (30)
console.log(Math.min(10, 20, 30)) // Devuelve el número más pequeño de los argumentos (10)
console.log(Math.sqrt(64)) // Devuelve la raíz cuadrada de un número (8)
console.log(Math.pow(2, 3)) // Devuelve la base elevada al exponente (8)
console.log(Math.random()) // Devuelve un número pseudoaleatorio entre 0 (inclusive) y 1 (exclusivo)
console.log(Math.random() * 1000)